### ISSUE TITLE
有赞: 介绍暂时性死区(一面)

### ISSUE THREAD

**Issue by yingpengsha** [frontend9/fe9-interview#12]
**To：**
yingpengsha

**面试公司：**
有赞

**面试环节：**
一面

**问题：**
介绍暂时性死区

**Comment by yingpengsha** [comment]
**答案：**

只要块级作用域内存在let、const命令，它所声明的变量就“绑定”（binding）这个区域，不再受外部的影响。

其本质就是，只要进入当前作用域，所要使用的变量就已经存在，但是不可获取，只有等到声明变量的那一行代码出现，才可以获取和使用该变量。

ES6 规定暂时性死区和 let 、const语句不出现变量提升，主要是为了减少运行时的错误，防止在变量声明前就是用这个变量，从而导致意料之外的行为

**解答思路：**

虽然面试官只问了 **暂时性死区** 一个概念，但其实考核的内容包括let、const、变量提升、作用域链等内容。

首先导致暂时性死区出现，是因为作用域内出现了 let 和 const 命令。
与之相反的 var 命令并不会出现暂时性死区的现象。

以下举例说明

**let**

```javascript
var num = 1;
if (true) {
  num = 'a'; // Error: Uncaught ReferenceError: num is not defined
  let num;
}
```

因为在 if 中声明了一个局部变量 num , 导致暂时性死区，if 里的 num 则与这个块级作用域绑定，不再受全局变量 num 影响，同时 let 不存在变量提升，所以在 let 前赋值的 num 是非法的。**const与之同理**。

**相关内容**

- [ECMAScript 6 入门 - let 和 const 命令](http://es6.ruanyifeng.com/#docs/let#%E6%9A%82%E6%97%B6%E6%80%A7%E6%AD%BB%E5%8C%BA)

**Comment by johanazhu** [comment]
![image](https://user-images.githubusercontent.com/24203037/116655478-bffeec00-a9bd-11eb-9a02-aca7c57aa6a5.png)

开了下脑洞，知识串起来就不难知道面试官的意图了
