### ISSUE TITLE
To acodercc: 前端开发中用到哪些设计模式 （沪江）

### ISSUE THREAD

**Issue by Tom0121** [frontend9/fe9-interview#22]
### To：
https://github.com/acodercc

 面试公司：
未知

 面试环节：
未知

问题：
前端开发中用到哪些设计模式

解答：
在平时开发中会用以下五种设计模式

- 单例模式   

- 观察者模式

- 工厂模式

- 命令模式

- 职责链模式

**Comment by acodercc** [comment]
1. 请按面试题模板创建issue
2. 目前我被#17点名答题，名下有进行中的问题，不能再对我提出问题，请在提问前先线下向被提问者沟通，是否在答题中。
