### ISSUE TITLE
To littleKnave: 实现一个Promise.prototype.first（今日头条）

### ISSUE THREAD

**Issue by AlexZ33** [frontend9/fe9-interview#28]
### To：

https://github.com/AlexZ33

### 面试公司：
今日头条，可视化部门。

### 面试环节：
一面

### 问题：
```
// （1.）最短时间内找出（2.）响应速度最快且（3.）成功的接口。
// 实现 findFatest 函数。

const urls = [
    'https://www.toutiao.com/a',
    'https://www.toutiao.com/b',
    'https://www.toutiao.com/bb',
    'https://www.toutiao.com/d',
    'https://www.toutiao.com/e',
]
findFatest(urls).then(url => console.log(url)
```

### 备注：
这是面试后自己的总结，抛砖引玉。
建议大家思考后有了自己的答案在看我的思路对不对。
[面试题，实现一个Promise.first](https://zhuanlan.zhihu.com/p/59316214)

**Comment by acodercc** [comment]
暂时close，
1. 非互面小组正式成员只能点名自己
2. 高质量的面试问答，会被引导成为正式成员
3. 正式成员可以点名正式成员小组内的其他非答题状态成员


规则请参见github repo首页： https://github.com/frontend9/fe9-interview/edit/master/README.md
