### ISSUE TITLE
requestAnimationFrame 的回调间隔是怎么被设定的

### ISSUE THREAD

**Issue by tapir-dream** [frontend9/fe9-interview#3]
**To：**
cc

**面试公司：**
家里蹲科技

**面试环节：**
一面

**问题：**
requestAnimationFrame 的回调间隔是怎么被设定的，请用某一个浏览器的具体代码来说明。

**自己的答案：**
自己完全不会啊……

**Comment by acodercc** [comment]
请认真阅读规则
1.  非九部成员要先To自己一个面试题自己回答噢
2. 只能To名下没有open状态的面试题的组员
3. 标题格式应该为To:xx 问题标题
